
export enum AppStatus {
  IDLE = 'IDLE',
  CONFIG_ERROR = 'CONFIG_ERROR',
  REQUESTING_CAMERA = 'REQUESTING_CAMERA',
  CAMERA_DENIED = 'CAMERA_DENIED',
  STREAMING = 'STREAMING',
  CAPTURING = 'CAPTURING',
  SENDING = 'SENDING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}
